### PR TITLE
Automatically run deploy && postrun before executing apply

### PR DESCRIPTION
**Pull request by jacksgt**
Otherwise the configuration code is never updated

Should ExecStartPre be allowed to fail or should the service abort in that case?

### CODE REVIEW

**Comment by martialblog** [comment]
Probably good to know when the scripts fail...

**Comment by jacksgt** [comment]
> Probably good to know when the scripts fail...
Sure, we absolutely need to know that.

But the question was more concerned around the puppet run itself: should puppet not ensure the system is an particular state, just because it can't fetch updates from the repos? (e.g. there is no network connection, website is down, ...)

**Comment by martialblog** [comment]
:+1: looking good

**Comment by jacksgt** [comment]
Solution: use a separate service for fetching module updates and for applying the configuration (the latter service depends on the former one)

**Pull request merged**
